# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2bd02124345c7d617f4d59c03ec494e3"
application_url = "https://walnut-medications-party-fraction.trycloudflare.com"
embedded = true
name = "thankyou"
handle = "thankyou-24"

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, read_customers, write_customers, read_orders"

[auth]
redirect_urls = [
  "https://walnut-medications-party-fraction.trycloudflare.com/auth/callback",
  "https://walnut-medications-party-fraction.trycloudflare.com/auth/shopify/callback",
  "https://walnut-medications-party-fraction.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "naga-tech-store.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[app_proxy]
url = "https://walnut-medications-party-fraction.trycloudflare.com"
subpath = "thankyou"
prefix = "a"
